version: "3"
services:
  rabbitmq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmqstats_data:/bitnami"
volumes:
  rabbitmqstats_data:
    driver: local
